# Documentation http://doc.gitlab.com/ci/yaml/README.html
# Syntax Checker https://ci.yb.lmax/lint

"ruby1.9.3-p551":
  script:
    - 'export RBENV_VERSION=1.9.3-p551'
    - 'ruby -v'
    - 'bundle install --path vendor/bundle --without system_tests'
    - 'bundle exec rake lint validate spec SPEC_OPTS="--format documentation"'

"ruby 2.1.9":
  script:
    - 'export RBENV_VERSION=2.1.9'
    - 'ruby -v'
    - 'bundle install --path vendor/bundle --without system_tests'
    - 'bundle exec rake lint validate spec SPEC_OPTS="--format documentation"'

